### PR TITLE
Use limit=0 in query to retrieve just the results metadata

### PR DESCRIPTION
**Pull request by zachgarwood**
As per the Pagination section in our API documentation: http://api.artic.edu/docs/#pagination

### CODE REVIEW

**Comment by web-dev-trev** [comment]
image

**Comment by trevinalonzo** [comment]
https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMWxscDdnYWRhcHRiMnkweTVkNWlybG5keDVnZmlxd2UyM2FiY2s5diZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7JvlHfd7C2GDr7zfZF/giphy.gif

**Comment by zachgarwood** [comment]
Stop trying to make `git fetch` happen. It's not going to happen!

**Review by nikhiltri — APPROVED** [review]
Looks good! ⭐

**Pull request merged**
